#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);


// MAIL_MAILER=smtp
// MAIL_HOST=smtp.gmail.com
// MAIL_PORT=465
// MAIL_USERNAME=udochukwunnaemeka35@gmail.com
// MAIL_PASSWORD=klcmzgjvxdwfymcf
// MAIL_ENCRYPTION=ssl
// MAIL_FROM_ADDRESS="udochukwunnaemeka35@gmail.com"
// MAIL_FROM_NAME="Absnews"
