<?php

return [
    'page_title' => 'Conditions générales',
    'last_updated' => 'Dernière mise à jour : :date',

    's1_title' => '1. Acceptation des présentes conditions.',
    's1_body' => 'Les présentes Conditions générales (les « Conditions ») régissent votre accès à Ledger et votre utilisation de celui-ci, y compris notre site web, l\'expérience mobile et toutes les fonctionnalités liées au compte, aux paiements, aux cartes et à l\'assistance (ensemble, le « Service »). En créant un compte ou en utilisant le Service, vous acceptez d\'être lié par les présentes Conditions ainsi que par toute politique qui y est mentionnée. Si vous n\'acceptez pas ces Conditions, ne créez pas de compte et n\'utilisez pas le Service.',

    's2_title' => '2. Admissibilité.',
    's2_body' => 'Pour ouvrir et détenir un compte Ledger, vous devez avoir au moins 18 ans, être capable de conclure un contrat contraignant, et pouvoir fournir un document d\'identité valide délivré par un gouvernement ainsi qu\'une adresse résidentielle permanente sur demande. Nous pouvons refuser d\'ouvrir un compte, ou fermer un compte existant, si nous ne parvenons pas à vérifier votre identité, si vous figurez sur une liste de sanctions ou de surveillance gouvernementale, ou si l\'ouverture ou le maintien du compte exposerait Ledger à un risque juridique ou réglementaire.',

    's3_title' => '3. Votre compte.',
    's3_body' => 'Les soldes des comptes Ledger ne sont pas détenus directement par Ledger en tant que banque. Les fonds sont détenus dans des comptes fiduciaires communs auprès d\'une ou plusieurs banques partenaires assurées par la FDIC, et vos fonds sont admissibles à l\'assurance-dépôts « pass-through » de la FDIC jusqu\'à la limite applicable, sous réserve des règles de la FDIC, du cumul avec tout autre fonds que vous détenez auprès de la même banque partenaire, et d\'une éventuelle défaillance de la banque partenaire. Ledger est elle-même une entreprise de technologie financière, et non une banque agréée. Vous ne pouvez détenir qu\'un seul compte personnel, sauf accord contraire écrit de notre part, et le compte ne peut pas être utilisé pour recevoir des fonds pour le compte d\'une entreprise, d\'une fiducie ou d\'une autre personne sans notre consentement écrit préalable.',

    's4_title' => '4. Vérification d\'identité et limites de compte.',
    's4_body' => 'La loi fédérale exige que les fournisseurs de services financiers obtiennent, vérifient et enregistrent les informations qui identifient chaque personne ouvrant un compte. Nous pouvons vous demander de soumettre une pièce d\'identité avec photo, un selfie ou un justificatif de domicile, et nous pouvons restreindre les montants de transfert, l\'émission de cartes ou d\'autres fonctionnalités jusqu\'à ce que ces informations soient examinées et approuvées. Nous pouvons revérifier périodiquement vos informations et suspendre les fonctionnalités concernées si une demande d\'informations actualisées reste sans réponse.',

    's5_title' => '5. Virements et paiements.',
    's5_body' => 'Le Service prend en charge plusieurs façons de transférer de l\'argent, chacune soumise aux limites, aux heures limites et à l\'examen qui vous sont indiqués au moment de la transaction : (a) les virements Ledger à Ledger, envoyés instantanément entre comptes Ledger ; (b) les virements bancaires externes, envoyés vers une banque liée ou sélectionnée dans le même pays à l\'aide des informations d\'acheminement de cette banque ; (c) les virements internationaux, envoyés vers une banque située hors de votre pays de résidence à l\'aide du code SWIFT/BIC de cette banque et du numéro de compte ou d\'IBAN, qui peuvent mettre plus de temps à arriver, être acheminés par des banques intermédiaires hors de notre contrôle, et être soumis à une conversion de devises au taux fixé au moment du traitement du virement ; (d) le paiement de factures, envoyé à un bénéficiaire que vous désignez ; et (e) les retraits et recharges, déplaçant de l\'argent entre votre solde Ledger et une carte ou un compte externe lié. Vous êtes responsable de la saisie complète et exacte des coordonnées du destinataire, d\'acheminement, SWIFT/BIC et de compte — Ledger ne peut pas annuler un virement qui a été correctement envoyé aux coordonnées que vous avez fournies, même si ces coordonnées étaient incorrectes. Un virement peut être retardé, retenu pour examen ou refusé s\'il est signalé pour suspicion de fraude, contrôle des sanctions ou solde disponible insuffisant.',

    's6_title' => '6. Virements programmés.',
    's6_body' => 'Un virement que vous programmez pour une date future n\'est soumis qu\'à la date sélectionnée et n\'est garanti que lorsqu\'il a effectivement quitté votre solde. Vous pouvez annuler un virement programmé à tout moment avant cette date depuis l\'historique de votre compte. Si votre solde disponible est insuffisant à la date programmée, le virement échouera et sera marqué en conséquence dans votre historique ; il vous incombe de vous assurer que des fonds suffisants sont disponibles.',

    's7_title' => '7. Frais.',
    's7_body' => 'Ledger ne facture actuellement aucuns frais pour les virements Ledger à Ledger, les virements bancaires externes, les virements internationaux, les retraits ou les recharges effectués via le Service. Votre banque liée, l\'émetteur de votre carte, ou une banque internationale destinataire peuvent tout de même appliquer leurs propres frais — y compris des frais de conversion de devises, de virement ou de banque intermédiaire pour les virements internationaux — qui échappent à notre contrôle et ne sont ni facturés ni conservés par Ledger. Si Ledger introduit des frais pour une fonctionnalité à l\'avenir, ces frais vous seront communiqués avant que vous ne confirmiez la transaction, et les présentes Conditions seront mises à jour pour les décrire.',

    's8_title' => '8. Cartes.',
    's8_body' => 'Si vous demandez une carte de débit virtuelle ou physique liée à votre solde Ledger, cette carte est soumise à approbation et, une fois émise, débite directement votre solde disponible au moment de chaque achat — il ne s\'agit pas d\'une ligne de crédit. Vous devez signaler immédiatement une carte perdue, volée ou compromise via la page Cartes afin qu\'elle puisse être gelée ou fermée ; vous restez responsable des transactions effectuées avant la réception du signalement, sauf dans les limites prévues par la loi applicable et la section 10 ci-dessous.',

    's9_title' => '9. Vos responsabilités et la sécurité du compte.',
    's9_body' => 'Vous êtes responsable de la sécurité de votre mot de passe, de votre code PIN de transaction, des codes d\'authentification à deux facteurs et de l\'appareil que vous utilisez pour accéder à Ledger, et vous ne devez les communiquer à personne. Vous devez nous informer immédiatement via la page Assistance si vous pensez que votre compte, votre mot de passe ou votre carte a été compromis, ou si vous remarquez une transaction que vous ne reconnaissez pas. Vous acceptez de maintenir vos coordonnées, votre adresse postale et vos documents d\'identité à jour et exacts dans nos dossiers.',

    's10_title' => '10. Erreurs et transactions non autorisées.',
    's10_body' => 'Si vous pensez qu\'un virement, un débit de carte ou une autre transaction a été effectué sans votre autorisation, ou que votre relevé de compte contient une erreur, contactez l\'Assistance dès que possible et au plus tard 60 jours après que l\'activité apparaît pour la première fois dans votre historique. Nous mènerons une enquête de bonne foi et pourrons restituer provisoirement les fonds pendant qu\'une enquête est en cours. Votre responsabilité pour une transaction non autorisée confirmée est limitée dans la mesure prévue par la loi applicable, à condition que vous nous en informiez rapidement et que vous n\'ayez pas agi frauduleusement ou avec négligence grave dans la protection de vos identifiants de compte.',

    's11_title' => '11. Usages interdits.',
    's11_body' => 'Vous acceptez de ne pas utiliser le Service à des fins illégales, notamment le blanchiment d\'argent, le financement du terrorisme, la fraude ou le contournement de sanctions ; d\'envoyer ou de recevoir des fonds auxquels vous n\'avez pas légalement droit ; de tenter d\'obtenir un accès non autorisé au compte d\'un autre utilisateur ou aux systèmes de Ledger ; ou de perturber le fonctionnement normal du Service. Nous pouvons refuser, retarder, annuler lorsque cela est possible, ou signaler toute transaction raisonnablement soupçonnée d\'enfreindre la présente section, et pouvons partager des informations avec les autorités ou les régulateurs comme l\'exige la loi.',

    's12_title' => '12. Statut, suspension et fermeture du compte.',
    's12_body' => 'Nous pouvons geler, restreindre, suspendre ou fermer votre compte, ou refuser une transaction spécifique, à notre discrétion — notamment pour nous conformer à la loi, enquêter sur une fraude ou un abus suspecté, répondre à une demande légale ou réglementaire, ou lorsque nous estimons raisonnablement que cela est nécessaire pour vous protéger, vous, un autre utilisateur, ou Ledger. Dans la mesure du possible, nous vous indiquerons la raison et comment nous joindre via la page Assistance. Vous pouvez fermer votre compte à tout moment en contactant l\'Assistance, à condition que votre solde soit nul ou ait été retiré et qu\'il n\'y ait aucune enquête en cours ni transaction en attente.',

    's13_title' => '13. Disponibilité du service ; avertissements.',
    's13_body' => 'Nous nous efforçons de maintenir le Service disponible et exact, mais le Service est fourni « tel quel » et nous ne garantissons pas qu\'il sera ininterrompu, exempt d\'erreurs ou disponible en permanence. Nous ne sommes pas responsables des retards ou défaillances causés par des circonstances échappant à notre contrôle raisonnable, y compris des interruptions chez une banque partenaire, un réseau de cartes ou un établissement intermédiaire, ou des cas de force majeure. Dans toute la mesure permise par la loi, la responsabilité globale de Ledger pour toute réclamation découlant de votre utilisation du Service est limitée au montant de la transaction à l\'origine de la réclamation, sauf lorsqu\'une réparation plus large est requise par une loi protégeant les comptes financiers des consommateurs.',

    's14_title' => '14. Règlement des différends.',
    's14_body' => 'En cas de désaccord entre vous et Ledger, nous vous demandons de contacter d\'abord l\'Assistance afin que nous puissions tenter de le résoudre directement — la plupart des problèmes peuvent être traités ainsi. Si un différend ne peut être résolu à l\'amiable, chaque partie peut se prévaloir de tout recours disponible en vertu de la loi applicable. Rien dans les présentes Conditions ne limite le droit que vous pourriez avoir, en vertu du droit de la protection des consommateurs, de soumettre un litige à votre régulateur étatique ou fédéral.',

    's15_title' => '15. Confidentialité.',
    's15_body' => 'Le traitement de vos informations personnelles et financières — ce que nous collectons, comment nous l\'utilisons, avec qui nous pouvons le partager (comme les banques partenaires, les fournisseurs de vérification d\'identité et les réseaux de cartes nécessaires au fonctionnement du Service), et les choix qui s\'offrent à vous — est décrit dans nos pratiques de confidentialité. Nous n\'utilisons vos informations d\'identité et de compte que pour exploiter, sécuriser et assurer la conformité légale du Service, et nous ne vendons pas vos informations personnelles.',

    's16_title' => '16. Modifications des présentes conditions.',
    's16_body' => 'Nous pouvons mettre à jour ces Conditions de temps à autre pour refléter des changements apportés au Service, à nos banques partenaires ou à la loi applicable. Lorsque nous apportons un changement important, nous mettrons à jour la date de « Dernière mise à jour » ci-dessus et, si la loi l\'exige, fournirons un avis supplémentaire. Continuer à utiliser le Service après l\'entrée en vigueur d\'un changement signifie que vous acceptez les Conditions mises à jour ; si vous n\'êtes pas d\'accord avec un changement, vous devez cesser d\'utiliser le Service et fermer votre compte.',

    's17_title' => '17. Loi applicable.',
    's17_body' => 'Les présentes Conditions sont régies par les lois des États-Unis et de l\'État dans lequel le siège des opérations de Ledger est situé, sans égard aux principes de conflit de lois, sauf lorsqu\'une loi différente doit s\'appliquer en vertu de la juridiction dans laquelle vous résidez.',

    's18_title' => '18. Nous contacter.',
    's18_body' => 'Les questions concernant les présentes Conditions, votre compte ou une transaction spécifique peuvent être envoyées à tout moment via la page :support_link.',
    'support_link_text' => 'Assistance',
];
