<?php

return [
    'page_title' => 'Allgemeine Geschäftsbedingungen',
    'last_updated' => 'Zuletzt aktualisiert: :date',

    's1_title' => '1. Annahme dieser Bedingungen.',
    's1_body' => 'Diese Allgemeinen Geschäftsbedingungen ("Bedingungen") regeln Ihren Zugriff auf und die Nutzung von Ledger, einschließlich unserer Website, der mobilen Nutzung und aller zugehörigen Konto-, Zahlungs-, Karten- und Support-Funktionen (zusammen der "Dienst"). Durch die Erstellung eines Kontos oder die Nutzung des Dienstes erklären Sie sich mit diesen Bedingungen und allen darin genannten Richtlinien einverstanden. Wenn Sie nicht einverstanden sind, erstellen Sie kein Konto und nutzen Sie den Dienst nicht.',

    's2_title' => '2. Berechtigung.',
    's2_body' => 'Um ein Ledger-Konto zu eröffnen und zu führen, müssen Sie mindestens 18 Jahre alt sein, in der Lage sein, einen verbindlichen Vertrag einzugehen, und auf Verlangen ein gültiges amtliches Ausweisdokument sowie eine dauerhafte Wohnadresse vorlegen können. Wir können die Eröffnung eines Kontos ablehnen oder ein bestehendes Konto schließen, wenn wir Ihre Identität nicht überprüfen können, Sie auf einer staatlichen Sanktions- oder Beobachtungsliste stehen, oder wenn die Eröffnung oder Führung des Kontos Ledger einem rechtlichen oder regulatorischen Risiko aussetzen würde.',

    's3_title' => '3. Ihr Konto.',
    's3_body' => 'Guthaben auf Ledger-Konten werden nicht direkt von Ledger als Bank gehalten. Die Gelder werden auf gepoolten Treuhandkonten bei einer oder mehreren FDIC-versicherten Partnerbanken gehalten, und Ihre Gelder sind bis zur geltenden Grenze für die "Pass-Through"-Einlagensicherung der FDIC berechtigt, vorbehaltlich der FDIC-Regeln, der Zusammenrechnung mit anderen Geldern, die Sie bei derselben Partnerbank halten, und einer eventuellen Insolvenz der Partnerbank. Ledger selbst ist ein Finanztechnologieunternehmen, keine zugelassene Bank. Sie dürfen nur ein persönliches Konto führen, sofern wir nichts anderes schriftlich vereinbaren, und das Konto darf nicht dazu verwendet werden, ohne unsere vorherige schriftliche Zustimmung Gelder im Namen eines Unternehmens, einer Treuhandgesellschaft oder einer anderen Person entgegenzunehmen.',

    's4_title' => '4. Identitätsprüfung und Kontolimits.',
    's4_body' => 'Bundesgesetze verlangen von Finanzdienstleistern, Informationen einzuholen, zu überprüfen und aufzuzeichnen, die jede Person identifizieren, die ein Konto eröffnet. Wir können Sie bitten, ein Ausweisdokument mit Foto, ein Selfie oder einen Adressnachweis vorzulegen, und wir können Überweisungsbeträge, die Ausgabe von Karten oder andere Funktionen einschränken, bis diese Informationen überprüft und genehmigt wurden. Wir können Ihre Angaben regelmäßig erneut überprüfen und betroffene Funktionen aussetzen, wenn eine Anfrage nach aktualisierten Informationen unbeantwortet bleibt.',

    's5_title' => '5. Überweisungen und Zahlungen.',
    's5_body' => 'Der Dienst unterstützt mehrere Möglichkeiten, Geld zu bewegen, jede unterliegt den Limits, Annahmeschlusszeiten und Prüfungen, die Ihnen zum Zeitpunkt der Transaktion angezeigt werden: (a) Ledger-zu-Ledger-Überweisungen, sofort zwischen Ledger-Konten gesendet; (b) externe Banküberweisungen, an eine verknüpfte oder ausgewählte Bank innerhalb desselben Landes unter Verwendung der Bankleitzahl dieser Bank; (c) internationale Überweisungen, an eine Bank außerhalb Ihres Heimatlandes unter Verwendung des SWIFT/BIC-Codes und der Konto- oder IBAN-Nummer dieser Bank, die länger dauern können, über zwischengeschaltete Banken außerhalb unserer Kontrolle geleitet werden können und einer Währungsumrechnung zu dem zum Zeitpunkt der Verarbeitung geltenden Kurs unterliegen können; (d) Rechnungszahlung, an einen von Ihnen bestimmten Zahlungsempfänger; und (e) Auszahlungen und Aufladungen, bei denen Geld zwischen Ihrem Ledger-Guthaben und einer verknüpften Karte oder einem externen Konto bewegt wird. Sie sind dafür verantwortlich, vollständige und korrekte Empfänger-, Bankleitzahl-, SWIFT/BIC- und Kontodaten einzugeben — Ledger kann eine Überweisung, die korrekt an die von Ihnen angegebenen Daten gesendet wurde, nicht rückgängig machen, selbst wenn diese Daten falsch waren. Eine Überweisung kann verzögert, zur Prüfung zurückgehalten oder abgelehnt werden, wenn sie wegen Betrugsverdachts, Sanktionsprüfung oder unzureichendem verfügbarem Guthaben markiert wird.',

    's6_title' => '6. Geplante Überweisungen.',
    's6_body' => 'Eine für ein zukünftiges Datum geplante Überweisung wird erst an dem ausgewählten Datum eingereicht und ist erst garantiert, wenn sie tatsächlich Ihr Guthaben verlassen hat. Sie können eine geplante Überweisung jederzeit vor diesem Datum über den Kontoverlauf stornieren. Wenn Ihr verfügbares Guthaben am geplanten Datum nicht ausreicht, schlägt die Überweisung fehl und wird entsprechend in Ihrem Verlauf gekennzeichnet; es liegt in Ihrer Verantwortung, sicherzustellen, dass ausreichende Mittel verfügbar sind.',

    's7_title' => '7. Gebühren.',
    's7_body' => 'Ledger erhebt derzeit keine Gebühr für Ledger-zu-Ledger-Überweisungen, externe Bankgeldüberweisungen, internationale Überweisungen, Auszahlungen oder Aufladungen, die über den Dienst veranlasst werden. Ihre verknüpfte Bank, der Kartenaussteller oder eine empfangende internationale Bank können dennoch eigene Gebühren erheben — einschließlich Währungsumrechnungs-, Überweisungs- oder Gebühren zwischengeschalteter Banken bei internationalen Überweisungen —, die außerhalb unserer Kontrolle liegen und nicht von Ledger erhoben oder einbehalten werden. Sollte Ledger in Zukunft eine Gebühr für eine Funktion einführen, wird Ihnen die entsprechende Gebühr vor Bestätigung der Transaktion mitgeteilt, und diese Bedingungen werden entsprechend aktualisiert.',

    's8_title' => '8. Karten.',
    's8_body' => 'Wenn Sie eine virtuelle oder physische Debitkarte beantragen, die mit Ihrem Ledger-Guthaben verknüpft ist, unterliegt diese Karte der Genehmigung und wird nach der Ausgabe bei jedem Kauf direkt von Ihrem verfügbaren Guthaben abgebucht — sie ist keine Kreditlinie. Sie müssen eine verlorene, gestohlene oder kompromittierte Karte sofort über die Karten-Seite melden, damit sie gesperrt oder geschlossen werden kann; Sie bleiben für Transaktionen verantwortlich, die vor Eingang der Meldung getätigt wurden, außer soweit durch geltendes Recht und Abschnitt 10 unten beschränkt.',

    's9_title' => '9. Ihre Verantwortlichkeiten und Kontosicherheit.',
    's9_body' => 'Sie sind dafür verantwortlich, Ihr Passwort, Ihre Transaktions-PIN, Zwei-Faktor-Authentifizierungscodes und das Gerät, mit dem Sie auf Ledger zugreifen, sicher aufzubewahren und diese mit niemandem zu teilen. Sie müssen uns unverzüglich über die Support-Seite benachrichtigen, wenn Sie vermuten, dass Ihr Konto, Passwort oder Ihre Karte kompromittiert wurde, oder wenn Ihnen eine Transaktion auffällt, die Sie nicht erkennen. Sie erklären sich damit einverstanden, Ihre Kontaktinformationen, Postanschrift und Ausweisdokumente aktuell und korrekt zu halten.',

    's10_title' => '10. Fehler und nicht autorisierte Transaktionen.',
    's10_body' => 'Wenn Sie glauben, dass eine Überweisung, Kartenbelastung oder andere Transaktion ohne Ihre Autorisierung vorgenommen wurde, oder dass Ihr Kontoauszug einen Fehler enthält, wenden Sie sich so schnell wie möglich, spätestens jedoch 60 Tage nachdem die Aktivität erstmals in Ihrem Verlauf erscheint, an den Support. Wir werden nach Treu und Glauben ermitteln und können während einer laufenden Untersuchung Gelder vorläufig wiederherstellen. Ihre Haftung für eine bestätigte nicht autorisierte Transaktion ist im nach geltendem Recht erforderlichen Umfang begrenzt, sofern Sie uns umgehend benachrichtigen und beim Schutz Ihrer Kontodaten nicht betrügerisch oder grob fahrlässig gehandelt haben.',

    's11_title' => '11. Verbotene Nutzungen.',
    's11_body' => 'Sie erklären sich damit einverstanden, den Dienst nicht für rechtswidrige Zwecke zu nutzen, einschließlich Geldwäsche, Terrorismusfinanzierung, Betrug oder Umgehung von Sanktionen; Gelder zu senden oder zu empfangen, auf die Sie keinen rechtmäßigen Anspruch haben; zu versuchen, unbefugten Zugriff auf das Konto eines anderen Nutzers oder auf die Systeme von Ledger zu erlangen; oder den normalen Betrieb des Dienstes zu stören. Wir können jede Transaktion, bei der wir vernünftigerweise annehmen, dass sie gegen diesen Abschnitt verstößt, ablehnen, verzögern, soweit möglich rückgängig machen oder melden, und wir können Informationen an Strafverfolgungsbehörden oder Aufsichtsbehörden weitergeben, soweit gesetzlich vorgeschrieben.',

    's12_title' => '12. Kontostatus, Sperrung und Schließung.',
    's12_body' => 'Wir können Ihr Konto nach eigenem Ermessen einfrieren, einschränken, sperren oder schließen oder eine bestimmte Transaktion ablehnen — unter anderem um geltendes Recht einzuhalten, vermuteten Betrug oder Missbrauch zu untersuchen, auf eine rechtliche oder behördliche Anfrage zu reagieren, oder wenn wir vernünftigerweise glauben, dass dies notwendig ist, um Sie, einen anderen Nutzer oder Ledger zu schützen. Soweit praktikabel, teilen wir Ihnen den Grund mit und wie Sie uns über die Support-Seite erreichen können. Sie können Ihr Konto jederzeit schließen, indem Sie sich an den Support wenden, sofern Ihr Guthaben null beträgt oder abgehoben wurde und keine laufende Untersuchung oder ausstehende Transaktion vorliegt.',

    's13_title' => '13. Verfügbarkeit des Dienstes; Haftungsausschlüsse.',
    's13_body' => 'Wir bemühen uns, den Dienst verfügbar und korrekt zu halten, aber der Dienst wird "wie besehen" bereitgestellt, und wir garantieren nicht, dass er unterbrechungsfrei, fehlerfrei oder jederzeit verfügbar ist. Wir haften nicht für Verzögerungen oder Ausfälle, die durch Umstände außerhalb unserer angemessenen Kontrolle verursacht werden, einschließlich Ausfällen bei einer Partnerbank, einem Kartennetzwerk oder einer zwischengeschalteten Institution, oder Fälle höherer Gewalt. Im gesetzlich zulässigen Höchstumfang ist die Gesamthaftung von Ledger für jeden Anspruch aus Ihrer Nutzung des Dienstes auf den Betrag der Transaktion beschränkt, die dem Anspruch zugrunde liegt, außer wenn ein weiterreichendes Rechtsmittel durch Gesetze zum Schutz von Verbraucherfinanzkonten vorgeschrieben ist.',

    's14_title' => '14. Streitbeilegung.',
    's14_body' => 'Sollte eine Meinungsverschiedenheit zwischen Ihnen und Ledger entstehen, bitten wir Sie, sich zunächst an den Support zu wenden, damit wir versuchen können, diese direkt zu lösen — die meisten Probleme lassen sich so klären. Kann ein Streit nicht informell beigelegt werden, kann jede Partei jedes nach geltendem Recht verfügbare Rechtsmittel in Anspruch nehmen. Nichts in diesen Bedingungen schränkt ein Recht ein, das Sie nach dem Verbraucherschutzrecht haben, einen Streit bei Ihrer staatlichen oder Bundesaufsichtsbehörde vorzubringen.',

    's15_title' => '15. Datenschutz.',
    's15_body' => 'Der Umgang mit Ihren persönlichen und finanziellen Informationen — was wir erheben, wie wir sie verwenden, mit wem wir sie teilen können (wie Partnerbanken, Anbieter von Identitätsprüfungen und Kartennetzwerke, die für den Betrieb des Dienstes erforderlich sind) und die Ihnen zur Verfügung stehenden Wahlmöglichkeiten — wird in unseren Datenschutzpraktiken beschrieben. Wir verwenden Ihre Identitäts- und Kontoinformationen ausschließlich zum Betrieb, zur Sicherung und zur Einhaltung des auf den Dienst anwendbaren Rechts, und wir verkaufen Ihre persönlichen Daten nicht.',

    's16_title' => '16. Änderungen dieser Bedingungen.',
    's16_body' => 'Wir können diese Bedingungen von Zeit zu Zeit aktualisieren, um Änderungen des Dienstes, unserer Partnerbanken oder des geltenden Rechts widerzuspiegeln. Bei einer wesentlichen Änderung aktualisieren wir das oben angegebene Datum "Zuletzt aktualisiert" und stellen, sofern gesetzlich vorgeschrieben, zusätzliche Hinweise bereit. Die fortgesetzte Nutzung des Dienstes nach Inkrafttreten einer Änderung bedeutet, dass Sie die aktualisierten Bedingungen akzeptieren; wenn Sie mit einer Änderung nicht einverstanden sind, sollten Sie die Nutzung des Dienstes beenden und Ihr Konto schließen.',

    's17_title' => '17. Anwendbares Recht.',
    's17_body' => 'Diese Bedingungen unterliegen dem Recht der Vereinigten Staaten und des Bundesstaats, in dem der Sitz von Ledgers Betrieb liegt, ohne Rücksicht auf Kollisionsnormen, außer wenn ein anderes Recht nach der Rechtsordnung anzuwenden ist, in der Sie ansässig sind.',

    's18_title' => '18. Kontaktieren Sie uns.',
    's18_body' => 'Fragen zu diesen Bedingungen, Ihrem Konto oder einer bestimmten Transaktion können jederzeit über die Seite :support_link gesendet werden.',
    'support_link_text' => 'Support',
];
