<?php

return [
    'page_title' => 'Algemene Voorwaarden',
    'last_updated' => 'Laatst bijgewerkt: :date',

    's1_title' => '1. Aanvaarding van deze Voorwaarden.',
    's1_body' => 'Deze Algemene Voorwaarden ("Voorwaarden") regelen uw toegang tot en gebruik van Ledger, inclusief onze website, mobiele ervaring en alle bijbehorende functies voor account, betalingen, kaarten en ondersteuning (gezamenlijk de "Dienst"). Door een account aan te maken of de Dienst te gebruiken, gaat u ermee akkoord gebonden te zijn aan deze Voorwaarden en alle daarin genoemde beleidsregels. Als u niet akkoord gaat, maak dan geen account aan en gebruik de Dienst niet.',

    's2_title' => '2. Geschiktheid.',
    's2_body' => 'Om een Ledger-account te openen en te behouden, moet u ten minste 18 jaar oud zijn, de bevoegdheid hebben om een juridisch bindend contract aan te gaan en op verzoek een geldig, door de overheid uitgegeven identiteitsbewijs en een vast woonadres kunnen verstrekken. Wij kunnen weigeren een account te openen of een bestaand account sluiten als wij uw identiteit niet kunnen verifiëren, als u voorkomt op een sanctie- of waarschuwingslijst van de overheid, of als het openen of behouden van het account Ledger juridisch of regelgevend risico zou opleveren.',

    's3_title' => '3. Uw account.',
    's3_body' => 'Saldi van Ledger-accounts worden niet rechtstreeks aangehouden door Ledger als bank. Middelen worden aangehouden in gepoolde trustrekeningen bij een of meer FDIC-verzekerde partnerbanken, en uw geld komt in aanmerking voor FDIC "pass-through"-depositoverzekering tot het toepasselijke maximum, onder voorbehoud van FDIC-regels, samenvoeging met ander geld dat u bij dezelfde partnerbank aanhoudt, en de mogelijkheid van faillissement van die partnerbank. Ledger zelf is een fintechbedrijf, geen erkende bank. U mag slechts één persoonlijk account aanhouden, tenzij wij schriftelijk anders overeenkomen, en het account mag niet worden gebruikt om namens een bedrijf, trust of andere persoon geld te ontvangen zonder onze voorafgaande schriftelijke toestemming.',

    's4_title' => '4. Identiteitsverificatie en accountlimieten.',
    's4_body' => 'De federale wetgeving vereist dat aanbieders van financiële diensten informatie verkrijgen, verifiëren en registreren waarmee iedere persoon die een account opent, kan worden geïdentificeerd. Wij kunnen u vragen een identiteitsbewijs met foto, een selfie of een adresbewijs in te dienen, en kunnen overmakingsbedragen, kaartuitgifte of andere functies beperken totdat deze informatie is geverifieerd en goedgekeurd. Wij kunnen uw gegevens periodiek opnieuw verifiëren en kunnen betrokken functies opschorten als een verzoek om informatie bij te werken onbeantwoord blijft.',

    's5_title' => '5. Overschrijvingen en betalingen.',
    's5_body' => 'De Dienst ondersteunt verschillende manieren om geld over te maken, elk onderhevig aan limieten, verwerkingstijden en controles die op het moment van de transactie aan u worden getoond: (a) Ledger-naar-Ledger-overschrijvingen, direct verzonden tussen Ledger-accounts; (b) externe bankoverschrijvingen, verzonden naar een gekoppelde of gekozen bank in hetzelfde land met behulp van de routegegevens van die bank; (c) internationale overschrijvingen, verzonden naar een bank buiten uw woonland met behulp van de SWIFT/BIC-code van die bank en rekeningnummer of IBAN, die langer kunnen duren, via tussenliggende banken buiten onze controle kunnen gaan en onderworpen kunnen zijn aan valutaconversie tegen een wisselkoers die is vastgesteld op het moment dat de overschrijving wordt verwerkt; (d) betaling van rekeningen, verzonden naar de door u opgegeven begunstigde; en (e) opnames en opwaarderingen, waarbij geld wordt verplaatst tussen uw Ledger-saldo en een gekoppelde kaart of externe rekening. U bent verantwoordelijk voor het invoeren van volledige en nauwkeurige gegevens van de begunstigde, routegegevens, SWIFT/BIC en rekeninggegevens — Ledger kan een overschrijving die correct is verzonden naar de door u verstrekte gegevens niet terugdraaien, zelfs als die gegevens onjuist waren. Een overschrijving kan worden vertraagd, aangehouden voor beoordeling of geweigerd als deze wordt gemarkeerd als vermoedelijke fraude, sanctiecontrole of onvoldoende beschikbaar saldo.',

    's6_title' => '6. Geplande overschrijvingen.',
    's6_body' => 'Een overschrijving die u voor een toekomstige datum plant, wordt alleen op de gekozen datum ingediend en is niet gegarandeerd totdat deze daadwerkelijk van uw saldo is afgeschreven. U kunt een geplande overschrijving op elk moment vóór die datum annuleren via uw accountgeschiedenis. Als uw beschikbare saldo op de geplande datum onvoldoende is, mislukt de overschrijving en wordt dit dienovereenkomstig gemarkeerd in uw geschiedenis; het is uw verantwoordelijkheid om voldoende geld beschikbaar te hebben.',

    's7_title' => '7. Kosten.',
    's7_body' => 'Ledger brengt momenteel geen kosten in rekening voor Ledger-naar-Ledger-overschrijvingen, externe bankoverschrijvingen, internationale overschrijvingen, opnames of opwaarderingen die via de Dienst worden geïnitieerd. Uw gekoppelde bank, kaartuitgever of ontvangende internationale bank kan echter wel hun eigen kosten in rekening brengen — waaronder valutaconversie, bankoverschrijving of tussenbankkosten bij internationale overschrijvingen — die buiten onze controle vallen en niet door Ledger in rekening worden gebracht of behouden. Als Ledger in de toekomst kosten invoert voor een functie, zullen wij de toepasselijke kosten aan u bekendmaken voordat u de transactie bevestigt en deze Voorwaarden bijwerken om dit te beschrijven.',

    's8_title' => '8. Kaarten.',
    's8_body' => 'Als u een virtuele of fysieke debetkaart aanvraagt die is gekoppeld aan uw Ledger-saldo, is die kaart onderworpen aan goedkeuring en wordt deze, eenmaal uitgegeven, bij elke aankoop direct van uw beschikbare saldo afgeschreven — dit is geen kredietlijn. U moet een verloren, gestolen of gecompromitteerde kaart onmiddellijk melden via de pagina "Kaarten", zodat deze kan worden bevroren of gesloten; u blijft verantwoordelijk voor transacties die plaatsvinden voordat wij de melding ontvangen, behalve zoals beperkt door toepasselijk recht en Sectie 10 hieronder.',

    's9_title' => '9. Uw verantwoordelijkheden en accountbeveiliging.',
    's9_body' => 'U bent verantwoordelijk voor het veilig houden van uw wachtwoord, transactie-pincode, tweefactorauthenticatiecodes en het apparaat dat u gebruikt om toegang te krijgen tot Ledger, en gaat ermee akkoord deze met niemand te delen. U moet ons onmiddellijk op de hoogte stellen via de pagina "Ondersteuning" als u denkt dat uw account, wachtwoord of kaart is gecompromitteerd, of als u een transactie opmerkt die u niet herkent. U gaat ermee akkoord uw contactgegevens, postadres en identiteitsdocumenten actueel en nauwkeurig te houden in onze administratie.',

    's10_title' => '10. Fouten en ongeautoriseerde transacties.',
    's10_body' => 'Als u denkt dat een overschrijving, kaartkosten of andere transactie zonder uw toestemming is uitgevoerd, of dat uw rekeningafschrift een fout bevat, neem dan zo snel mogelijk contact op met Ondersteuning, maar niet later dan 60 dagen nadat die activiteit voor het eerst in uw geschiedenis verscheen. Wij zullen te goeder trouw onderzoek doen en kunnen geld tijdelijk herstellen tijdens het onderzoek. Uw aansprakelijkheid voor een bevestigde ongeautoriseerde transactie is beperkt tot de mate die vereist is door toepasselijk recht, mits u ons tijdig op de hoogte heeft gesteld en niet frauduleus of met grove nalatigheid heeft gehandeld bij het beschermen van uw accountgegevens.',

    's11_title' => '11. Verboden gebruik.',
    's11_body' => 'U stemt ermee in de Dienst niet te gebruiken voor illegale doeleinden, waaronder witwassen, financiering van terrorisme, fraude of het omzeilen van sancties; geld te verzenden of te ontvangen waarop u geen wettelijk recht heeft; te proberen ongeautoriseerde toegang te krijgen tot het account van een andere gebruiker of tot de systemen van Ledger; of de normale werking van de Dienst te verstoren. Wij kunnen elke transactie waarvan redelijkerwijs wordt vermoed dat deze deze sectie schendt, weigeren, vertragen, waar mogelijk terugdraaien of melden, en kunnen informatie delen met wetshandhavings- of toezichthoudende instanties indien wettelijk vereist.',

    's12_title' => '12. Accountstatus, opschorting en sluiting.',
    's12_body' => 'Wij kunnen uw account naar eigen goeddunken bevriezen, beperken, opschorten of sluiten, of een specifieke transactie weigeren — onder meer om aan de wet te voldoen, vermoedelijke fraude of misbruik te onderzoeken, te reageren op een juridisch of regelgevend verzoek, of wanneer wij redelijkerwijs van mening zijn dat dit nodig is om u, een andere gebruiker of Ledger te beschermen. Waar praktisch mogelijk, laten wij u weten wat de reden is en hoe u contact met ons kunt opnemen via de pagina "Ondersteuning". U kunt uw account op elk moment sluiten door contact op te nemen met Ondersteuning, op voorwaarde dat uw saldo nul is of is opgenomen, en er geen lopend onderzoek of openstaande transactie is.',

    's13_title' => '13. Beschikbaarheid van de dienst; disclaimers.',
    's13_body' => 'Wij streven ernaar de beschikbaarheid en nauwkeurigheid van de Dienst te handhaven, maar de Dienst wordt geleverd "zoals deze is" en wij garanderen niet dat deze ononderbroken, foutloos of altijd beschikbaar is. Wij zijn niet aansprakelijk voor vertragingen of storingen veroorzaakt door omstandigheden buiten onze redelijke controle, waaronder storingen bij een partnerbank, kaartnetwerk of tussenliggende instelling, of overmacht. Voor zover maximaal toegestaan door de wet, is de totale aansprakelijkheid van Ledger voor elke claim die voortvloeit uit uw gebruik van de Dienst beperkt tot het bedrag van de transactie die aanleiding gaf tot de claim, tenzij wetgeving ter bescherming van consumentenrekeningen een ruimere vergoeding vereist.',

    's14_title' => '14. Geschillenbeslechting.',
    's14_body' => 'Als er een meningsverschil ontstaat tussen u en Ledger, vragen wij u eerst contact op te nemen met Ondersteuning, zodat wij kunnen proberen het rechtstreeks op te lossen — de meeste problemen kunnen op deze manier worden behandeld. Als een geschil niet informeel kan worden opgelost, kan elke partij elk rechtsmiddel inzetten dat beschikbaar is onder het toepasselijke recht. Niets in deze Voorwaarden beperkt enig recht dat u heeft onder consumentenbeschermingswetgeving om een geschil voor te leggen aan uw staats- of federale toezichthouder.',

    's15_title' => '15. Privacy.',
    's15_body' => 'Hoe wij omgaan met uw persoonlijke en financiële informatie — wat wij verzamelen, hoe wij het gebruiken, met wie wij het kunnen delen (zoals partnerbanken, aanbieders van identiteitsverificatie en kaartnetwerken die nodig zijn om de Dienst te laten werken), en de keuzes die voor u beschikbaar zijn — worden beschreven in onze privacypraktijken. Wij gebruiken uw identiteits- en accountinformatie uitsluitend voor het exploiteren, beveiligen en naleven van de wetgeving die van toepassing is op de Dienst, en wij verkopen uw persoonlijke informatie niet.',

    's16_title' => '16. Wijzigingen in deze Voorwaarden.',
    's16_body' => 'Wij kunnen deze Voorwaarden van tijd tot tijd bijwerken om wijzigingen in de Dienst, onze partnerbanken of de toepasselijke wetgeving te weerspiegelen. Wanneer wij een materiële wijziging aanbrengen, werken wij de bovenstaande datum "Laatst bijgewerkt" bij en, indien wettelijk vereist, geven wij een aanvullende kennisgeving. Voortgezet gebruik van de Dienst nadat een wijziging van kracht wordt, betekent dat u de bijgewerkte Voorwaarden accepteert; als u niet akkoord gaat met een wijziging, dient u het gebruik van de Dienst te staken en uw account te sluiten.',

    's17_title' => '17. Toepasselijk recht.',
    's17_body' => 'Deze Voorwaarden worden beheerst door de wetgeving van de Verenigde Staten en de staat waar Ledger operationeel is gevestigd, ongeacht conflicterende rechtsbeginselen, tenzij een ander recht van toepassing moet zijn volgens het rechtsgebied van uw woonplaats.',

    's18_title' => '18. Neem contact met ons op.',
    's18_body' => 'Vragen over deze Voorwaarden, uw account of een specifieke transactie kunnen op elk moment naar ons worden gestuurd via de pagina :support_link.',
    'support_link_text' => 'Ondersteuning',
];
