<?php

return [
    'page_title' => 'Termini e Condizioni',
    'last_updated' => 'Ultimo aggiornamento: :date',

    's1_title' => '1. Accettazione dei presenti termini.',
    's1_body' => 'I presenti Termini e Condizioni ("Termini") disciplinano l\'accesso e l\'uso di Ledger, incluso il nostro sito web, l\'esperienza mobile e tutte le funzionalità correlate di account, pagamento, carta e assistenza (congiuntamente, il "Servizio"). Creando un account o utilizzando il Servizio, accetti di essere vincolato dai presenti Termini e da qualsiasi politica in essi richiamata. Se non accetti, non creare un account né utilizzare il Servizio.',

    's2_title' => '2. Idoneità.',
    's2_body' => 'Per aprire e detenere un account Ledger devi avere almeno 18 anni, essere in grado di stipulare un contratto vincolante e poter fornire un documento d\'identità valido rilasciato da un governo e un indirizzo di residenza permanente su richiesta. Possiamo rifiutare l\'apertura di un account, o chiudere un account esistente, se non riusciamo a verificare la tua identità, se compari in un elenco governativo di sanzioni o sorveglianza, o se l\'apertura o il mantenimento dell\'account esporrebbe Ledger a un rischio legale o normativo.',

    's3_title' => '3. Il tuo account.',
    's3_body' => 'I saldi degli account Ledger non sono detenuti direttamente da Ledger come banca. I fondi sono detenuti in conti fiduciari collettivi presso una o più banche partner assicurate dalla FDIC, e i tuoi fondi sono idonei all\'assicurazione sui depositi "pass-through" della FDIC fino al limite applicabile, soggetta alle regole della FDIC, all\'aggregazione con eventuali altri fondi che detieni presso la stessa banca partner, e a un\'eventuale insolvenza della banca partner. Ledger stessa è una società di tecnologia finanziaria, non una banca autorizzata. Puoi detenere un solo account personale, salvo diverso accordo scritto, e l\'account non può essere utilizzato per ricevere fondi per conto di un\'azienda, un trust o un\'altra persona senza il nostro previo consenso scritto.',

    's4_title' => '4. Verifica dell\'identità e limiti dell\'account.',
    's4_body' => 'La legge federale richiede ai fornitori di servizi finanziari di ottenere, verificare e registrare le informazioni che identificano ogni persona che apre un account. Potremmo chiederti di inviare un documento d\'identità con foto, un selfie o una prova di indirizzo, e potremmo limitare gli importi dei trasferimenti, l\'emissione di carte o altre funzionalità fino a quando tali informazioni non saranno esaminate e approvate. Potremmo riverificare periodicamente le tue informazioni e sospendere le funzionalità interessate se una richiesta di informazioni aggiornate rimane senza risposta.',

    's5_title' => '5. Trasferimenti e pagamenti.',
    's5_body' => 'Il Servizio supporta diverse modalità di trasferimento del denaro, ciascuna soggetta ai limiti, agli orari limite e alla verifica mostrati al momento della transazione: (a) trasferimenti Ledger-to-Ledger, inviati istantaneamente tra account Ledger; (b) bonifici bancari esterni, inviati a una banca collegata o selezionata all\'interno dello stesso paese utilizzando le informazioni di instradamento di quella banca; (c) trasferimenti internazionali, inviati a una banca al di fuori del tuo paese di origine utilizzando il codice SWIFT/BIC di quella banca e il numero di conto o IBAN, che potrebbero richiedere più tempo per arrivare, essere instradati attraverso banche intermediarie al di fuori del nostro controllo, ed essere soggetti a conversione valutaria al tasso stabilito al momento dell\'elaborazione del trasferimento; (d) pagamento di bollette, inviato a un beneficiario da te designato; ed (e) prelievi e ricariche, che spostano denaro tra il tuo saldo Ledger e una carta o un account esterno collegato. Sei responsabile dell\'inserimento di dati completi e accurati del destinatario, di instradamento, SWIFT/BIC e del conto — Ledger non è in grado di annullare un trasferimento inviato correttamente ai dati che hai fornito, anche se tali dati erano errati. Un trasferimento può essere ritardato, trattenuto per verifica o rifiutato se contrassegnato per sospetta frode, controllo sanzioni o saldo disponibile insufficiente.',

    's6_title' => '6. Trasferimenti programmati.',
    's6_body' => 'Un trasferimento che programmi per una data futura viene inviato solo alla data selezionata e non è garantito finché non è effettivamente uscito dal tuo saldo. Puoi annullare un trasferimento programmato in qualsiasi momento prima di quella data dalla cronologia del tuo account. Se il tuo saldo disponibile è insufficiente alla data programmata, il trasferimento fallirà e verrà contrassegnato di conseguenza nella tua cronologia; è tua responsabilità assicurarti che siano disponibili fondi sufficienti.',

    's7_title' => '7. Commissioni.',
    's7_body' => 'Ledger attualmente non addebita alcuna commissione per trasferimenti Ledger-to-Ledger, bonifici bancari esterni, trasferimenti internazionali, prelievi o ricariche avviati tramite il Servizio. La tua banca collegata, l\'emittente della carta, o una banca internazionale ricevente potrebbero comunque applicare le proprie commissioni — incluse commissioni di conversione valutaria, di bonifico o di banche intermediarie sui trasferimenti internazionali — che sono al di fuori del nostro controllo e non sono addebitate né trattenute da Ledger. Se in futuro Ledger introdurrà una commissione per qualsiasi funzionalità, la commissione applicabile ti sarà comunicata prima di confermare la transazione, e i presenti Termini saranno aggiornati per descriverla.',

    's8_title' => '8. Carte.',
    's8_body' => 'Se richiedi una carta di debito virtuale o fisica collegata al tuo saldo Ledger, tale carta è soggetta ad approvazione e, una volta emessa, addebita direttamente il tuo saldo disponibile al momento di ogni acquisto — non è una linea di credito. Devi segnalare immediatamente una carta smarrita, rubata o compromessa utilizzando la pagina Carte in modo che possa essere bloccata o chiusa; rimani responsabile delle transazioni effettuate prima della ricezione della segnalazione, salvo quanto limitato dalla legge applicabile e dalla sezione 10 qui sotto.',

    's9_title' => '9. Le tue responsabilità e la sicurezza dell\'account.',
    's9_body' => 'Sei responsabile della sicurezza della tua password, del PIN delle transazioni, dei codici di autenticazione a due fattori e del dispositivo che utilizzi per accedere a Ledger, e di non condividerli con nessuno. Devi avvisarci immediatamente tramite la pagina Assistenza se ritieni che il tuo account, la password o la carta siano stati compromessi, o se noti una transazione che non riconosci. Accetti di mantenere aggiornate e corrette le tue informazioni di contatto, l\'indirizzo postale e i documenti d\'identità nei nostri archivi.',

    's10_title' => '10. Errori e transazioni non autorizzate.',
    's10_body' => 'Se ritieni che un trasferimento, un addebito sulla carta o un\'altra transazione siano stati effettuati senza la tua autorizzazione, o che il tuo estratto conto contenga un errore, contatta l\'Assistenza il prima possibile ed entro e non oltre 60 giorni dalla prima comparsa dell\'attività nella tua cronologia. Indagheremo in buona fede e potremmo ripristinare provvisoriamente i fondi mentre un\'indagine è in corso. La tua responsabilità per una transazione non autorizzata confermata è limitata nella misura richiesta dalla legge applicabile, a condizione che tu ci avvisi tempestivamente e non abbia agito in modo fraudolento o con negligenza grave nel proteggere le tue credenziali dell\'account.',

    's11_title' => '11. Usi vietati.',
    's11_body' => 'Accetti di non utilizzare il Servizio per scopi illeciti, incluso il riciclaggio di denaro, il finanziamento del terrorismo, la frode o l\'elusione delle sanzioni; di inviare o ricevere fondi a cui non hai legittimamente diritto; di tentare di ottenere accesso non autorizzato all\'account di un altro utente o ai sistemi di Ledger; o di interferire con il normale funzionamento del Servizio. Possiamo rifiutare, ritardare, annullare ove possibile, o segnalare qualsiasi transazione ragionevolmente ritenuta in violazione di questa sezione, e possiamo condividere informazioni con le forze dell\'ordine o le autorità di regolamentazione come richiesto dalla legge.',

    's12_title' => '12. Stato, sospensione e chiusura dell\'account.',
    's12_body' => 'Possiamo congelare, limitare, sospendere o chiudere il tuo account, o rifiutare una specifica transazione, a nostra discrezione — anche per conformarci alla legge, indagare su sospette frodi o abusi, rispondere a una richiesta legale o normativa, o quando riteniamo ragionevolmente che ciò sia necessario per proteggere te, un altro utente o Ledger. Ove possibile, ti comunicheremo il motivo e come contattarci tramite la pagina Assistenza. Puoi chiudere il tuo account in qualsiasi momento contattando l\'Assistenza, a condizione che il tuo saldo sia zero o sia stato prelevato e non vi sia alcuna indagine in corso o transazione in sospeso.',

    's13_title' => '13. Disponibilità del servizio; limitazioni di responsabilità.',
    's13_body' => 'Ci impegniamo a mantenere il Servizio disponibile e accurato, ma il Servizio è fornito "così com\'è" e non garantiamo che sarà ininterrotto, privo di errori o disponibile in ogni momento. Non siamo responsabili per ritardi o guasti causati da circostanze al di fuori del nostro ragionevole controllo, incluse interruzioni presso una banca partner, una rete di carte o un istituto intermediario, o eventi di forza maggiore. Nella misura massima consentita dalla legge, la responsabilità aggregata di Ledger per qualsiasi reclamo derivante dal tuo utilizzo del Servizio è limitata all\'importo della transazione che ha dato origine al reclamo, salvo quando un rimedio più ampio sia richiesto dalla legge a tutela dei conti finanziari dei consumatori.',

    's14_title' => '14. Risoluzione delle controversie.',
    's14_body' => 'Se sorge un disaccordo tra te e Ledger, ti chiediamo di contattare prima l\'Assistenza in modo da poter tentare di risolverlo direttamente — la maggior parte dei problemi può essere gestita in questo modo. Se una controversia non può essere risolta informalmente, entrambe le parti possono ricorrere a qualsiasi rimedio disponibile ai sensi della legge applicabile. Nulla nei presenti Termini limita alcun diritto tu abbia ai sensi della legge sulla tutela dei consumatori di sollevare una controversia presso il tuo regolatore statale o federale.',

    's15_title' => '15. Privacy.',
    's15_body' => 'Il trattamento delle tue informazioni personali e finanziarie — cosa raccogliamo, come lo utilizziamo, con chi potremmo condividerlo (come banche partner, fornitori di verifica dell\'identità e reti di carte necessari per gestire il Servizio) e le scelte a tua disposizione — è descritto nelle nostre pratiche sulla privacy. Utilizziamo le tue informazioni di identità e account solo per gestire, proteggere e conformarci alla legge applicabile al Servizio, e non vendiamo le tue informazioni personali.',

    's16_title' => '16. Modifiche ai presenti termini.',
    's16_body' => 'Potremmo aggiornare periodicamente questi Termini per riflettere modifiche al Servizio, alle nostre banche partner o alla legge applicabile. Quando apportiamo una modifica sostanziale, aggiorneremo la data "Ultimo aggiornamento" sopra indicata e, ove richiesto dalla legge, forniremo un avviso aggiuntivo. Continuare a utilizzare il Servizio dopo l\'entrata in vigore di una modifica significa che accetti i Termini aggiornati; se non sei d\'accordo con una modifica, dovresti interrompere l\'utilizzo del Servizio e chiudere il tuo account.',

    's17_title' => '17. Legge applicabile.',
    's17_body' => 'I presenti Termini sono disciplinati dalle leggi degli Stati Uniti e dello stato in cui ha sede l\'attività di Ledger, senza riguardo ai principi di conflitto di leggi, salvo quando una legge diversa debba essere applicata in base alla giurisdizione in cui risiedi.',

    's18_title' => '18. Contattaci.',
    's18_body' => 'Le domande su questi Termini, sul tuo account o su una transazione specifica possono essere inviate in qualsiasi momento tramite la pagina :support_link.',
    'support_link_text' => 'Assistenza',
];
